### ISSUE TITLE
support for Pandas.to_excel ?

### ISSUE THREAD

**Issue by johnoscott** [Polyconseil/xlsx_streaming#8]
can I use xlsx_streaming as an engine for Pandas.to_excel ?

Pandas supports a different XLSX writer and I was wondering if it would work

**Comment by dbaty** [comment]
I am not familiar with Pandas, but it's obvious that you will need some plumbing.

I looked (very) quickly at [pandas.io.excel._openpyxl._Openpyxl.write_cells](https://github.com/pandas-dev/pandas/blob/afe7f1de9bb03a9a1a5122a6e32458225f8c007a/pandas/io/excel/_openpyxl.py#L401). It takes the cells of a `DataFrame` object (that it gets from [pandas.io.formats.excel.ExcelFormatter.get_formatted_cells](https://github.com/pandas-dev/pandas/blob/afe7f1de9bb03a9a1a5122a6e32458225f8c007a/pandas/io/formats/excel.py#L687)). I guess that you could try to build rows from the formatter, and then pass them to `xlsx_streaming.stream_queryset_as_xlsx()`.

Very roughly:

```python
import xlsx_streaming
from pandas.io.formats.excel import ExcelFormatter

formatter = ExcelFormatter(df)

def generate_rows(formatter):
    last_row_number = 1
    row = []
    for cell in formatter.get_formated_cells():
        if cell.row != last_row_number:
            yield row
            last_row_number += 1
            row = []
        row.append(cell.val)

stream = xlsx_streaming.stream_queryset_as_xlsx(generate_rows(formatter))
```

That produces an invalid XLSX file. I am not keen to dig more, so someone will have to figure out why. That could be you. :) If you find a solution, we will be happy to include it in the documentation.

**Comment by johnoscott** [comment]
Thats a great start - thanks. I will see if I can get it working.

**Comment by dbaty** [comment]
I am not sure there is anything actionable here for now, so I'll close this issue. Do not hesitate to reopen if you find a solution and would like to add it to the documentation.
